global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "article-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["article-service:8080"]

  - job_name: "comment-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["commentservice:8080"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]